import { launch } from './cdp.mjs'
import { BASE, idb, noHorizontalScroll, reporter, seedExistingUser, setValue } from './helpers.mjs'

const r = reporter()
const b = await launch(9351)
try {
  await b.mobile()
  await b.send('Network.enable')
  await b.send('Network.setBypassServiceWorker', { bypass: true })

  // ---------- Existing user: nothing changes until they choose
  await seedExistingUser(b, { tasks: [{ id: 'old1', title: 'Tarefa antiga', projectId: null, dueDate: '', priority: 'none', status: 'todo', completedAt: null }] })
  await b.goto(BASE)
  let text = await b.text()
  const sheet = await b.eval(`document.querySelector('[role=dialog]')?.innerText ?? ''`)
  r.check('usuário existente: aviso mostra só as seções novas', sheet.includes('Chegaram seções novas') && sheet.includes('Caixa de entrada') && !sheet.includes('Financeiro'))
  r.check('usuário existente: nada é ligado sozinho (sem botão +)', !(await b.eval(`!!document.querySelector('[aria-label="Capturar na caixa de entrada"]')`)))
  await b.click('Caixa de entrada', '[role=switch]')
  await b.click('Pronto')
  // Início has no floating "+" (it has its own actions): the capture shows on screens like Mais.
  await b.goto(BASE + '#/more')
  await b.sleep(600)
  r.check('ao ligar a seção, o botão + aparece', await b.eval(`!!document.querySelector('[aria-label="Capturar na caixa de entrada"]')`))
  const nav = await b.eval(`[...document.querySelectorAll('nav[aria-label="Navegação principal"] a')].map(a => a.textContent.trim())`)
  r.check('abas inferiores continuam as mesmas', JSON.stringify(nav) === JSON.stringify(['Início', 'Financeiro', 'Projetos', 'Tarefas', 'Mais']), JSON.stringify(nav))
  const oldTask = await idb(b, 'tasks', 'old1')
  r.check('tarefa antiga intacta e sem campo novo obrigatório', oldTask.title === 'Tarefa antiga' && !('notes' in oldTask))
  await b.goto(BASE)
  text = await b.text()
  r.check('aviso aparece só uma vez', !text.includes('Chegaram seções novas'))

  // ---------- Quick capture
  await b.goto(BASE + '#/more')
  await b.sleep(600)
  await b.click('Capturar na caixa de entrada')
  await setValue(b, 'textarea[aria-label="O que você quer guardar?"]', 'Ligar para João amanhã')
  await b.shot('inbox-captura')
  await b.click('Guardar para organizar depois')
  await b.sleep(400)
  let items = await idb(b, 'inbox')
  r.check('captura salva como item não organizado', items.length === 1 && items[0].status === 'open' && items[0].text === 'Ligar para João amanhã')

  await b.goto(BASE + '#/inbox')
  text = await b.text()
  r.check('caixa de entrada lista o item', text.includes('Ligar para João amanhã') && text.includes('1 para organizar'))
  await b.shot('inbox-lista')

  // ---------- Convert into a task (reuses the existing task form)
  await b.click('Organizar')
  await b.click('Tarefa', 'button')
  const prefilled = await b.eval(`({ title: [...document.querySelectorAll('label')].find(l => l.textContent.startsWith('Título'))?.querySelector('input')?.value, date: document.querySelector('input[type=date]')?.value })`)
  const tomorrow = await b.eval(`(() => { const p = Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(Date.now()+86400000)).map(x=>[x.type,x.value])); return p.year+'-'+p.month+'-'+p.day })()`)
  r.check('formulário de tarefa vem preenchido (título e "amanhã")', prefilled.title === 'Ligar para João amanhã' && prefilled.date === tomorrow, JSON.stringify(prefilled))
  await b.shot('inbox-converter-tarefa')
  await b.click('Criar tarefa', 'button[type=submit]')
  await b.sleep(500)
  const tasks = await idb(b, 'tasks')
  const created = tasks.find((t) => t.title === 'Ligar para João amanhã')
  items = await idb(b, 'inbox')
  r.check('tarefa criada no sistema de tarefas existente', Boolean(created) && created.dueDate === tomorrow)
  r.check('item fica organizado com vínculo para a tarefa (não é apagado)', items.length === 1 && items[0].status === 'done' && items[0].convertedTo?.collection === 'tasks' && items[0].convertedTo?.id === created?.id)
  await b.goto(BASE + '#/tasks')
  r.check('tarefa aparece em Tarefas', (await b.text()).includes('Ligar para João amanhã'))

  // ---------- Convert into a note; and "Já resolvi"
  await b.goto(BASE + '#/inbox')
  await b.click('Capturar na caixa de entrada', 'button')
  await setValue(b, 'textarea[aria-label="O que você quer guardar?"]', 'Ideia: app de receitas\ncom lista de compras')
  await b.click('Guardar para organizar depois')
  await b.click('Organizar')
  await b.click('Anotação', 'button')
  await b.click('Salvar', 'button[type=submit]')
  await b.sleep(500)
  const notes = await idb(b, 'notes')
  r.check('vira anotação com título e texto', notes.some((n) => n.title === 'Ideia: app de receitas' && n.body === 'com lista de compras'))
  await b.click('Capturar na caixa de entrada', 'button')
  await setValue(b, 'textarea[aria-label="O que você quer guardar?"]', 'Pensar no fim de semana')
  await b.click('Guardar para organizar depois')
  await b.click('Organizar')
  await b.click('Já resolvi')
  items = await idb(b, 'inbox')
  r.check('"Já resolvi" organiza sem criar nada', items.filter((i) => i.status === 'done').length === 3 && items.find((i) => i.text === 'Pensar no fim de semana').convertedTo === null)
  text = await b.text()
  r.check('caixa vazia e histórico de organizados', text.includes('Nada para organizar') && text.toUpperCase().includes('ORGANIZADOS · 3'))
  r.check('sem rolagem horizontal (390px)', await noHorizontalScroll(b))
  await b.shot('inbox-vazia')

  // ---------- Desktop: sidebar capture
  await b.desktop()
  await b.goto(BASE + '#/inbox')
  r.check('computador: botão Capturar no menu lateral', await b.eval(`[...document.querySelectorAll('aside button')].some(x => x.textContent.trim() === 'Capturar')`))
  r.check('sem rolagem horizontal (1366px)', await noHorizontalScroll(b))
  await b.shot('inbox-desktop')
} catch (err) {
  r.results.push('ERROR ' + err.message)
  await b.shot('inbox-erro')
} finally {
  const failed = r.print(b)
  b.close()
  process.exit(failed ? 1 : 0)
}
