import { launch } from './cdp.mjs'

const BASE = 'http://localhost:4318/nucleo/'
const MOCK = 'http://localhost:54399'
const results = []
const check = (name, ok, extra = '') => results.push(`${ok ? 'PASS' : 'FAIL'} ${name}${extra ? ' — ' + extra : ''}`)
const state = async () => (await fetch(MOCK + '/__state')).json()
const setVal = (b, selector, value) =>
  b.eval(`(() => { const el = document.querySelector(${JSON.stringify(selector)}); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el, ${JSON.stringify(value)}); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)

async function signUpAndConfirm(b, email) {
  await b.click('Criar conta')
  await b.fill('E-mail', email)
  await b.fill('Senha', 'senha1234')
  await b.fill('Repita a senha', 'senha1234')
  await b.click('Criar conta', 'button[type=submit]')
  await b.sleep(800)
  await b.fill('Código do e-mail', '123456')
  await b.click('Confirmar', 'button[type=submit]')
  await b.sleep(2000)
}

async function signIn(b, email) {
  await b.fill('E-mail', email)
  await b.fill('Senha', 'senha1234')
  await b.click('Entrar', 'button[type=submit]')
  await b.sleep(2500)
}

const A = await launch(9340)
const B = await launch(9341)
try {
  for (const b of [A, B]) {
    await b.mobile()
    await b.send('Network.enable')
    await b.send('Network.setBypassServiceWorker', { bypass: true })
  }

  // ---------- Device A: existing no-account data
  await A.goto(BASE + 'favicon.svg')
  await A.eval(`new Promise((resolve) => { const req = indexedDB.open('nucleo', 1); req.onupgradeneeded = () => { const db = req.result; for (const n of ['transactions','goals','clients','projects','tasks','tools','accounts','notes','portfolio']) db.createObjectStore(n, { keyPath: 'id' }); db.createObjectStore('meta') }; req.onsuccess = () => { const db = req.result; const tx = db.transaction(['notes','accounts','meta','transactions'], 'readwrite'); const now = new Date().toISOString(); tx.objectStore('meta').put({ onboarded: true, modulesReviewed: true, baseCurrency: 'EUR', initialBalance: 50000, startedAt: now, rates: null, manualRates: {}, lastBackupAt: null }, 'settings'); tx.objectStore('notes').put({ id: 'n-local', createdAt: now, updatedAt: now, title: 'Nota do aparelho', body: '', pinned: false }); tx.objectStore('transactions').put({ id: 't-local', createdAt: now, updatedAt: now, type: 'out', amount: 1000, currency: 'EUR', baseAmount: -1000, reason: 'Café' }); tx.objectStore('accounts').put({ id: 'a-local', createdAt: now, updatedAt: now, name: 'Email', clientId: null, projectId: null, link: '', email: 'x@y.z', username: '', password: 'senha-antiga', notes: '' }); tx.oncomplete = () => { db.close(); resolve(1) } } })`)
  await A.goto(BASE + '#/account')
  let text = await A.text()
  check('sem login: dados só no aparelho, com opção de entrar', text.includes('Seus dados estão só neste aparelho'))
  await signUpAndConfirm(A, 'ana@teste.com')
  text = await A.text()
  check('após confirmar o e-mail, oferece migração (não automática) citando a conta', text.includes('Dados neste aparelho') && text.includes('ana@teste.com') && text.includes('Não enviar'))
  check('migração avisa sobre senha sem criptografia', text.includes('senha(s) de Contas estão sem criptografia'))
  await A.shot('t3-migracao')
  let s = await state()
  check('nada foi enviado antes da confirmação', s.records.length === 0)
  await A.click('Criar o cofre da conta')
  await A.fill('Senha do cofre', 'cofre-da-ana-1')
  await A.fill('Repita a senha do cofre', 'cofre-da-ana-1')
  await A.click('Gerar código de recuperação', 'label')
  await A.click('Entendi', 'label')
  await A.click('Criar cofre', 'button[type=submit]')
  await A.sleep(2500)
  await A.click('Enviar para a conta')
  await A.sleep(3000)
  s = await state()
  const anaId = s.users.find((u) => u.email === 'ana@teste.com').id
  const anaRows = s.records.filter((r) => r.user_id === anaId)
  check('migração enviou os 3 registros', anaRows.length === 3, String(anaRows.length))
  check('senha chegou ao servidor só criptografada', !JSON.stringify(s.records).includes('senha-antiga') && anaRows.find((r) => r.collection === 'accounts').data.secret?.ct)
  const anaSettings = s.settings.find(([id]) => id === anaId)?.[1]
  check('configurações do aparelho copiadas, com o cofre', anaSettings?.data.initialBalance === 50000 && anaSettings?.data.vault?.byPassword)
  text = await A.text()
  check('após migrar, conta mostra registros conferidos', text.includes('Sim, conferidos'))
  const localStill = await A.eval(`new Promise(r => { const q = indexedDB.open('nucleo'); q.onsuccess = () => { const g = q.result.transaction('notes').objectStore('notes').count(); g.onsuccess = () => { q.result.close(); r(g.result) } } })`)
  check('cópia local mantida após migrar', localStill === 1)

  // Re-run migration: no duplicates
  await A.goto(BASE + '#/account')
  await A.click('Enviar de novo (não duplica)')
  await A.sleep(500)
  await A.click('Abrir o cofre da conta').catch(() => {})
  if ((await A.text()).includes('Desbloquear cofre')) {
    await A.fill('Senha do cofre', 'cofre-da-ana-1')
    await A.click('Desbloquear', 'button[type=submit]')
    await A.sleep(2000)
  }
  await A.click('Enviar para a conta')
  await A.sleep(2500)
  s = await state()
  check('migrar de novo não duplica', s.records.filter((r) => r.user_id === anaId).length === 3)

  // New note on A, synced
  await A.goto(BASE + '#/notes')
  text = await A.text()
  check('nota do aparelho aparece na conta', text.includes('Nota do aparelho'))

  // ---------- Device B: same account
  await B.goto(BASE)
  await B.click('Entrar ou criar conta')
  await signIn(B, 'ana@teste.com')
  await B.goto(BASE + '#/notes')
  text = await B.text()
  check('outro aparelho baixa os dados da conta', text.includes('Nota do aparelho'))
  await B.goto(BASE + '#/accounts')
  text = await B.text()
  check('no outro aparelho a senha continua protegida pelo cofre', text.includes('Cofre fechado') && !text.includes('senha-antiga'))
  await B.click('Mostrar senha')
  await B.fill('Senha do cofre', 'cofre-da-ana-1')
  await B.click('Desbloquear', 'button[type=submit]')
  await B.sleep(2500)
  await B.click('Mostrar senha')
  text = await B.text()
  check('mesma senha do cofre abre em outro aparelho', text.includes('senha-antiga'))
  // Delete the note on B, see it disappear on A
  await B.goto(BASE + '#/notes')
  await B.click('Nota do aparelho')
  await B.click('Excluir')
  await B.eval(`[...document.querySelectorAll('button')].find(b => b.textContent.trim() === 'Excluir' && !b.getAttribute('aria-label')).click()`)
  await B.sleep(2000)
  await A.goto(BASE + '#/account')
  await A.click('Agora')
  await A.sleep(1500)
  await A.goto(BASE + '#/notes')
  text = await A.text()
  check('exclusão no aparelho B chega ao aparelho A', !text.includes('Nota do aparelho'))

  // ---------- Offline edit on B
  await fetch(MOCK + '/__offline?v=1')
  await B.goto(BASE + '#/tasks')
  await B.click('Nova', 'button')
  await B.fill('Título', 'Feita offline')
  await B.click('Criar tarefa', 'button[type=submit]')
  await B.sleep(2500)
  s = await state()
  check('sem servidor, a tarefa fica na fila (não se perde)', !s.records.some((r) => r.data?.title === 'Feita offline'))
  await fetch(MOCK + '/__offline?v=0')
  await B.goto(BASE + '#/account')
  await B.click('Agora')
  await B.sleep(2000)
  s = await state()
  check('ao voltar a conexão, a fila é enviada', s.records.some((r) => r.data?.title === 'Feita offline'))

  // ---------- AI flow on B (mock returns an overlapping block)
  await B.goto(BASE + '#/settings')
  await B.click('Seções visíveis')
  await B.click('Rotina', '[role=switch]')
  await B.click('Fechar', 'button')
  await B.goto(BASE + '#/planner')
  await B.click('Só rotina')
  await B.click('Continuar')
  await B.click('Adicionar compromisso')
  await B.click('Continuar')
  await B.click('Continuar')
  await B.click('Adicionar atividade')
  await B.fill('Atividade', 'Leitura')
  await B.click('Continuar')
  await B.click('Continuar')
  const disabled = await B.eval(`[...document.querySelectorAll('button')].find(b => b.textContent.includes('Gerar proposta com IA')).disabled`)
  await B.click('Gerar proposta com IA')
  text = await B.text()
  check('sem consentimento não envia', text.includes('Confirme que concorda') && !disabled)
  await B.click('Concordo', 'label')
  await B.click('Gerar proposta com IA')
  await B.sleep(2500)
  text = await B.text()
  check('proposta vira rascunho; bloco sobreposto ao trabalho é descartado', text.includes('Proposta da IA') && text.includes('Descartado pela verificação') && text.includes('conflita'))
  await B.shot('t3-proposta')

  // ---------- Shared device: A signs out, another person signs in
  await A.goto(BASE + '#/account')
  await A.click('Sair desta conta')
  await A.click('Sair', 'button')
  await A.sleep(2000)
  const cacheGone = await A.eval(`indexedDB.databases ? indexedDB.databases().then(l => l.map(d => d.name)) : []`)
  check('ao sair, a cópia da conta é removida do aparelho', !cacheGone.some((n) => n.startsWith('nucleo-u-')), JSON.stringify(cacheGone))
  text = await A.text()
  // After signing out the sign-in screen opens (to enter another account); "Voltar" leads to the device's no-account data.
  check('ao sair, abre a tela de entrada', text.includes('Esqueci minha senha'))
  await A.click('Voltar')
  await A.sleep(800)
  await A.goto(BASE + '#/account')
  await A.sleep(600)
  text = await A.text()
  check('voltando, os dados sem conta do aparelho continuam lá', text.includes('Seus dados estão só neste aparelho'))
  await signUpAndConfirm(A, 'bruno@teste.com')
  text = await A.text()
  check('outra pessoa no mesmo aparelho: oferta aparece, não associa sozinho', text.includes('Dados neste aparelho') && text.includes('bruno@teste.com'))
  await A.click('Não enviar')
  await A.eval(`[...document.querySelectorAll('button')].filter(b => b.textContent.trim() === 'Não enviar').at(-1).click()`)
  await A.sleep(1500)
  text = await A.text()
  check('conta nova de outra pessoa começa vazia (onboarding)', text.includes('Seu centro de organização'))
  s = await state()
  const brunoId = s.users.find((u) => u.email === 'bruno@teste.com').id
  check('nenhum registro de Ana foi copiado para Bruno', s.records.filter((r) => r.user_id === brunoId).length === 0)
  // Direct request as Bruno for Ana's data (the mock partitions by JWT; real isolation is RLS, tested in Postgres)
  const brunoToken = await A.eval(`JSON.parse(localStorage.getItem('nucleo:auth')).access_token`)
  const direct = await (await fetch(`${MOCK}/rest/v1/records?select=*&user_id=eq.${anaId}`, { headers: { Authorization: `Bearer ${brunoToken}` } })).json()
  check('requisição direta de Bruno não traz dados de Ana (mock)', Array.isArray(direct) && direct.length === 0)
} catch (err) {
  results.push('ERROR ' + err.message)
  await A.shot('t3-error-a')
  await B.shot('t3-error-b')
} finally {
  console.log(results.join('\n'))
  console.log('LOGS A:\n' + A.logs.slice(0, 10).join('\n'))
  console.log('LOGS B:\n' + B.logs.slice(0, 10).join('\n'))
  A.close()
  B.close()
}
