import { launch } from './cdp.mjs'

const BASE = 'http://localhost:4317/nucleo/'
const b = await launch(9335)
const results = []
const check = (name, ok, extra = '') => results.push(`${ok ? 'PASS' : 'FAIL'} ${name}${extra ? ' — ' + extra : ''}`)
const idb = (store, id) =>
  b.eval(`new Promise(r => { const q = indexedDB.open('nucleo'); q.onsuccess = () => { const s = q.result.transaction(${JSON.stringify(store)}).objectStore(${JSON.stringify(store)}); const g = ${id ? `s.get(${JSON.stringify(id)})` : 's.getAll()'}; g.onsuccess = () => { q.result.close(); r(g.result) } } })`)

try {
  await b.mobile()
  await b.send('Network.enable')
  await b.send('Network.setBypassServiceWorker', { bypass: true })
  await b.goto(BASE)
  let text = await b.text()
  check('onboarding sem conta configurada mostra só "Começar"', text.includes('Começar') && !text.includes('Entrar ou criar conta'))
  await b.click('Começar')
  const radios = await b.eval(`[...document.querySelectorAll('[role=radio]')].map(r => r.textContent.replace(/\\s+/g,' ').trim() + (r.getAttribute('aria-checked') === 'true' ? ' *' : ''))`)
  check('moedas iniciais BRL, USD, EUR com BRL selecionado', radios.length === 3 && radios[0].includes('BRL') && radios[0].endsWith('*') && radios[1].includes('USD') && radios[2].includes('EUR'), JSON.stringify(radios))
  await b.shot('t2-moeda')
  await b.click('Outra moeda…')
  await b.eval(`(() => { const el = document.querySelector('input[type=search]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'dirham'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.sleep(300)
  text = await b.text()
  check('busca de moeda por nome encontra AED', text.includes('AED'))
  await b.eval(`(() => { const el = document.querySelector('input[type=search]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'chf'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.sleep(300)
  text = await b.text()
  check('busca de moeda por código encontra CHF', text.includes('Franco suíço'))
  await b.click('Fechar', 'button')
  await b.click('Continuar')
  await b.shot('t2-secoes')
  // Turn on Sales, Subscribers, Routine, Meals
  for (const name of ['Vendas', 'Assinantes', 'Rotina', 'Alimentação']) await b.click(name, '[role=switch]')
  await b.click('Continuar')
  await b.eval(`(() => { const el = document.querySelector('input[aria-label="Saldo inicial"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'2000'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.click('Entrar')
  await b.sleep(800)
  text = await b.text()
  check('entra no painel em BRL', text.includes('R$') && text.includes('2.000'))
  const settings = await idb('meta', 'settings')
  check('escolhas salvas (base BRL, seções)', settings.baseCurrency === 'BRL' && settings.modules.sales && settings.modules.routine && settings.modulesReviewed === true)

  // ---------- Vendas
  await b.goto(BASE + '#/sales')
  await b.click('Registrar venda')
  await b.fill('Ou nome de quem comprou', 'Maria')
  await b.fill('Produto', 'Bolo de cenoura')
  await b.fill('Quantidade', '2')
  await b.eval(`(() => { const el = [...document.querySelectorAll('input[inputmode=decimal]')].find(i => i.placeholder === '0,00' && !i.closest('label')?.textContent.includes('recebeu')); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'120'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.fill('Já recebeu quanto?', '50')
  await b.click('Registrar venda', 'button[type=submit]')
  await b.sleep(600)
  text = await b.text()
  check('venda com pagamento parcial: falta R$ 70', text.includes('falta R$ 70,00') && text.includes('R$ 70,00'))
  await b.click('Maria')
  await b.click('Registrar pagamento')
  await b.eval(`(() => { const el = document.querySelector('input[placeholder="70"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'80'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.click('Adicionar', 'button')
  await b.sleep(400)
  text = await b.text()
  check('pagamento acima do que falta é bloqueado', text.includes('passa do que falta'))
  await b.eval(`(() => { const el = document.querySelector('input[placeholder="70"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'70'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.click('Adicionar', 'button')
  await b.sleep(600)
  text = await b.text()
  check('quitada após pagar o restante', text.includes('Quitado'))
  await b.shot('t2-venda')
  const sales = await idb('sales')
  check('venda guarda histórico com 2 pagamentos e nenhum saldo duplicado', sales.length === 1 && sales[0].payments.length === 2 && !('remaining' in sales[0]))
  await b.click('Fechar', 'button')

  // ---------- Assinantes
  await b.goto(BASE + '#/subscribers')
  await b.click('Cadastrar produto')
  await b.fill('Nome', 'App Treino')
  await b.click('Salvar', 'button[type=submit]')
  await b.click('+ Novo plano')
  await b.fill('Nome do plano', 'Mensal')
  await b.eval(`(() => { const el = document.querySelector('input[inputmode=decimal]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'30'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.click('Salvar', 'button[type=submit]')
  await b.click('+ Novo plano')
  await b.fill('Nome do plano', 'Anual')
  await b.click('Anual', '[role=radio]')
  await b.eval(`(() => { const el = document.querySelector('input[inputmode=decimal]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'240'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.click('Salvar', 'button[type=submit]')
  for (const [name, plan] of [['João', 'Mensal'], ['Ana', 'Anual']]) {
    await b.click('Assinante', 'button')
    await b.eval(`(() => { const sel = [...document.querySelectorAll('select')].find(s => [...s.options].some(o => o.textContent.startsWith(${JSON.stringify(plan)}))); const opt = [...sel.options].find(o => o.textContent.startsWith(${JSON.stringify(plan)})); Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(sel, opt.value); sel.dispatchEvent(new Event('change',{bubbles:true})) })()`)
    await b.fill('Nome', name)
    await b.click('Salvar', 'button[type=submit]')
    await b.sleep(300)
  }
  text = await b.text()
  check('projeção: R$ 30 mensal + R$ 20 equivalente do anual = R$ 50/mês', text.includes('R$ 50,00') && text.includes('≈R$ 20,00'))
  check('anual: R$ 360 estimado + R$ 240', text.includes('R$ 600,00/ano'))
  check('recebido separado (nada ainda)', text.toUpperCase().includes('RECEBIDO DE VERDADE'))
  await b.shot('t2-assinantes')

  // ---------- Tarefas + Hoje
  await b.goto(BASE + '#/tasks')
  await b.eval(`void 0`)
  text = await b.text()
  await b.click(text.includes('Nova tarefa') ? 'Nova tarefa' : 'Nova')
  await b.fill('Título', 'Ligar para fornecedor')
  const today = await b.eval(`new Date().toLocaleDateString('sv')`)
  await b.fill('Prazo', today)
  await b.fill('Horário', '23:50')
  await b.click('Criar tarefa', 'button[type=submit]')
  await b.goto(BASE + '#/today')
  text = await b.text()
  check('Hoje mostra a tarefa com horário', text.includes('Ligar para fornecedor') && !text.includes('está escondida') && text.toUpperCase().includes('TAREFAS DE HOJE'))
  await b.shot('t2-hoje')
  await b.click('Concluir tarefa')
  await b.sleep(1200)
  const tasks = await idb('tasks')
  check('concluir em Hoje atualiza a tarefa original', tasks.length === 1 && tasks[0].status === 'done' && tasks[0].completedAt)

  // ---------- Rotina (manual, sem IA)
  await b.goto(BASE + '#/routine')
  await b.click('Começar')
  await b.click('Só rotina')
  await b.click('Continuar') // sono
  await b.click('Adicionar compromisso')
  await b.click('Continuar') // compromissos (padrão: sai 8h, almoço 12-13, chega 18h)
  await b.click('Continuar') // treinos
  await b.click('Adicionar atividade')
  await b.fill('Atividade', 'Leitura')
  await b.click('Continuar') // atividades
  await b.click('Continuar') // descanso
  text = await b.text()
  check('revisão informa o que vai para a IA e pede consentimento', text.includes('O que será enviado para a IA') && text.includes('Concordo'))
  check('sem conta, IA desativada e montar à mão disponível', text.includes('A IA funciona com uma conta conectada'))
  await b.shot('t2-revisao')
  await b.click('Montar à mão')
  await b.sleep(800)
  text = await b.text()
  check('rascunho com horários fixos calculados', text.includes('Rascunho') && text.includes('08:30–12:00') && text.includes('12:00–13:00'))
  await b.click('Aprovar e salvar')
  await b.sleep(500)
  text = await b.text()
  check('rotina salva', text.includes('Toque no círculo para marcar como feito'))
  await b.shot('t2-rotina')

  // ---------- Alimentação (manual) com alergia
  await b.goto(BASE + '#/planner')
  await b.click('Só rotina', 'button') // opens choice
  await b.click('Rotina + alimentação')
  // jump through routine steps
  for (let i = 0; i < 5; i++) await b.click('Continuar')
  await b.click('Continuar') // objetivo
  await b.click('Amendoim', 'button')
  await b.click('Continuar') // alergias
  await b.click('Continuar') // gostos
  await b.click('Continuar') // cozinha
  await b.click('Usar horários da minha rotina')
  const times = await b.eval(`[...document.querySelectorAll('input[type=time]')].map(i => i.value)`)
  check('horários das refeições vêm da rotina (almoço 12:00, jantar 19:00)', times.includes('12:00') && times.includes('19:00'), JSON.stringify(times))
  await b.click('Continuar') // horários
  await b.click('Continuar') // saúde
  await b.click('Montar à mão')
  await b.sleep(800)
  await b.goto(BASE + '#/meals')
  text = await b.text()
  check('rascunho de refeições criado', text.includes('Rascunho'))
  await b.click('Almoço', 'button')
  await b.fill('Itens', 'Arroz\nFrango com molho de amendoim')
  await b.click('Salvar', 'button[type=submit]')
  await b.sleep(400)
  text = await b.text()
  check('item com alergênico é bloqueado na edição manual', text.includes('não combina com: Amendoim'))
  await b.fill('Itens', 'Arroz\nFrango grelhado')
  await b.click('Salvar', 'button[type=submit]')
  await b.sleep(400)
  await b.eval(`(() => { const el = document.querySelector('input[placeholder="Adicionar item"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'Paçoca'); el.dispatchEvent(new Event('input',{bubbles:true})) })()`)
  await b.click('Adicionar', 'button')
  await b.sleep(400)
  text = await b.text()
  check('lista de compras também bloqueia alergênico', text.includes('não combina com: Amendoim'))
  await b.click('Aprovar e salvar')
  await b.shot('t2-alimentacao')

  // ---------- Lembretes
  await b.goto(BASE + '#/reminders')
  text = await b.text()
  check('lembretes: sem servidor, explica e mantém lembretes no app', text.includes('lembretes aparecem dentro do app') && (text.includes('não foi configurado') || text.includes('não oferece')))
  await b.click('Rotina e treinos', '[role=switch]')
  text = await b.text()
  check('próximos lembretes calculados da rotina', text.toUpperCase().includes('PRÓXIMOS LEMBRETES'))
  await b.shot('t2-lembretes')

  // ---------- Mais / navegação
  await b.goto(BASE + '#/more')
  text = await b.text()
  check('Mais mostra só seções ligadas', text.includes('Vendas') && text.includes('Assinantes') && text.includes('Hoje') && !text.includes('Portfólio'))
  // hidden module by URL
  await b.goto(BASE + '#/portfolio')
  text = await b.text()
  check('seção escondida não abre por link (dados mantidos)', text.includes('está escondida'))

  // ---------- Desktop
  await b.desktop()
  await b.goto(BASE + '#/routine')
  await b.shot('t2-desktop-rotina')
  await b.goto(BASE + '#/today')
  await b.shot('t2-desktop-hoje')
  const overflow = await b.eval(`document.documentElement.scrollWidth > document.documentElement.clientWidth`)
  check('sem rolagem horizontal no desktop', !overflow)
  await b.mobile()
  await b.goto(BASE + '#/subscribers')
  const overflowM = await b.eval(`document.documentElement.scrollWidth > document.documentElement.clientWidth`)
  check('sem rolagem horizontal no celular', !overflowM)
} catch (err) {
  results.push('ERROR ' + err.message)
  await b.shot('t2-error')
} finally {
  console.log(results.join('\n'))
  console.log('LOGS:\n' + b.logs.slice(0, 15).join('\n'))
  b.close()
}
